name: check-markdown-links

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run everyday at 9:00 AM (See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07)
    - cron: '0 9 * * *'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdown-link-check:
    name: check-markdown-links/markdown-link-check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Required for github-pr-review reporter
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: 'false'

      - name: Check broken links
        uses: umbrelladocs/action-linkspector@652f85bc57bb1e7d4327260decc10aa68f7694c3 # v1.4.0
        with:
          filter_mode: nofilter
          config_file: .github/config/.linkspector.yml
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_level: any
